### ISSUE TITLE
Does this bundle support Symfony 5?

### ISSUE THREAD

**Issue by Tarasovych** [sensiolabs-de/rich-model-forms-bundle#79]
Hello!

I'm trying to use this bundle with Symfony 5.

What do I have:
`php -v`:
```
PHP 7.3.14 (cli) (built: Jan 27 2020 21:55:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
```
`composer.json`
```json
"require": {
        "php": "^7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "easycorp/easyadmin-bundle": "^2.3",
        "myclabs/php-enum": "^1.7",
        "sensiolabs-de/rich-model-forms-bundle": "^0.4.0",
        "symfony/console": "5.0.*",
        "symfony/dotenv": "5.0.*",
        "symfony/flex": "^1.3.1",
        "symfony/form": "5.0.*",
        "symfony/framework-bundle": "5.0.*",
        "symfony/http-client": "5.0.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "*",
        "symfony/security-bundle": "5.0.*",
        "symfony/twig-pack": "*",
        "symfony/validator": "5.0.*",
        "symfony/yaml": "5.0.*"
    }
```

I've set up a simple config:
```yml
easy_admin:
    entities:
        User:
            class: App\Entity\User

            new:
                fields:
                    - { property: name }

                form_options:
                    factory: App\Entity\User
```

I have an issue entering `new` view:

> Argument 2 passed to SensioLabs\RichModelForms\ExceptionHandling\FormExceptionHandler::__construct() must be an instance of Symfony\Component\Translation\TranslatorInterface or null, instance of Symfony\Component\Translation\DataCollectorTranslator given

Seems like its related to https://github.com/sensiolabs-de/rich-model-forms-bundle/commit/27d67bb98edbb9eb163d550eeef17fe1aed7123a

Ping me, if you would like to get a repository with reproducable example.

Thanks in advance!

**Comment by xabbuh** [comment]
Does it work if you change the constraint to `^0.5@dev` and update the package?

**Comment by Tarasovych** [comment]
@xabbuh sorry, can't tel you exactly, because right after installing new version I'm getting

> Could not resolve argument $authenticationUtils of "App\Controller\SecurityController:login()", maybe you forgot to register the controller as a service or missed tagging it with the "controller.service_arguments"?

My `services.yaml` left untouched:
```yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
```
an my controller is as it is in the documentation:
```php
class SecurityController extends AbstractController
{
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        $error = $authenticationUtils->getLastAuthenticationError();

        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render(
            'security/login.html.twig',
            [
                'last_username' => $lastUsername,
                'error' => $error
            ]
        );
    }

    public function logout(): void
    {
        return;
    }
}
```
